import { useEffect, useState } from "react";
import { Alert, Button, Card, Col, Form, Row, Tab, Table, Tabs } from "react-bootstrap";
import { createCompra, createProveedor, getCompras, getProveedores, getReporte, type Compra, type Proveedor } from "../../api/comprasService";
import { getProductos } from "../../api/inventarioService";
import type { Producto } from "../../types/inventario";
import { mostrarError, mostrarExito } from "../../lib/alerts";

export default function ComprasReportesPage() {
  const [proveedores,setProveedores]=useState<Proveedor[]>([]); const [productos,setProductos]=useState<Producto[]>([]); const [compras,setCompras]=useState<Compra[]>([]); const [reporte,setReporte]=useState<unknown>(null);
  const [proveedorId,setProveedorId]=useState(""); const [numero,setNumero]=useState(""); const [productoId,setProductoId]=useState(""); const [cantidad,setCantidad]=useState(1); const [precio,setPrecio]=useState(0); const [ruc,setRuc]=useState(""); const [nombre,setNombre]=useState(""); const [tipoReporte,setTipoReporte]=useState("ventas");
  const cargar=async()=>{try{const [p,pr,c]=await Promise.all([getProveedores(),getProductos(),getCompras()]);setProveedores(p);setProductos(pr);setCompras(c);}catch{mostrarError("No se pudieron cargar compras e inventario.")}};
  // La carga inicial sincroniza la pantalla con la API al montar.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void cargar()},[]);
  const proveedor=async()=>{try{await createProveedor({proveedor_ruc:ruc,proveedor_nombre:nombre});setRuc("");setNombre("");await cargar();mostrarExito("Proveedor creado.")}catch{mostrarError("No se pudo crear el proveedor.")}};
  const compra=async()=>{try{await createCompra({proveedor_id:Number(proveedorId),compra_numero:numero,detalles:[{producto_id:Number(productoId),cantidad,precio_unitario:precio}]});setNumero("");await cargar();mostrarExito("Compra registrada y stock actualizado.")}catch{mostrarError("No se pudo registrar la compra.")}};
  const cargarReporte=async()=>{try{setReporte(await getReporte(tipoReporte))}catch{mostrarError("No se pudo cargar el reporte.")}};
  return <div className="container-fluid pt-3"><h2>Compras y reportes</h2><Tabs defaultActiveKey="compras" className="mb-3"><Tab eventKey="compras" title="Registrar compra"><Card className="mb-3"><Card.Body><Row><Col md={3}><Form.Label>Proveedor</Form.Label><Form.Select value={proveedorId} onChange={e=>setProveedorId(e.target.value)}><option value="">Seleccione...</option>{proveedores.map(p=><option key={p.proveedor_id} value={p.proveedor_id}>{p.proveedor_nombre}</option>)}</Form.Select></Col><Col md={3}><Form.Label>Número</Form.Label><Form.Control value={numero} onChange={e=>setNumero(e.target.value)} /></Col><Col md={3}><Form.Label>Producto</Form.Label><Form.Select value={productoId} onChange={e=>setProductoId(e.target.value)}><option value="">Seleccione...</option>{productos.map(p=><option key={p.producto_id} value={p.producto_id}>{p.producto_nombre}</option>)}</Form.Select></Col><Col md={1}><Form.Label>Cant.</Form.Label><Form.Control type="number" min="1" value={cantidad} onChange={e=>setCantidad(Number(e.target.value))}/></Col><Col md={2}><Form.Label>Precio</Form.Label><Form.Control type="number" min="0.01" value={precio} onChange={e=>setPrecio(Number(e.target.value))}/></Col></Row><Button className="mt-3" onClick={compra}>Registrar compra</Button></Card.Body></Card><Card><Card.Body><Card.Title>Nuevo proveedor</Card.Title><Row><Col><Form.Control placeholder="RUC" value={ruc} onChange={e=>setRuc(e.target.value)}/></Col><Col><Form.Control placeholder="Nombre" value={nombre} onChange={e=>setNombre(e.target.value)}/></Col><Col><Button onClick={proveedor}>Guardar proveedor</Button></Col></Row></Card.Body></Card><Table className="mt-3" striped bordered><thead><tr><th>Número</th><th>Proveedor</th><th>Fecha</th><th>Total</th></tr></thead><tbody>{compras.map(c=><tr key={c.compra_id}><td>{c.compra_numero}</td><td>{c.proveedor.proveedor_nombre}</td><td>{new Date(c.compra_fecha).toLocaleDateString()}</td><td>${Number(c.compra_total).toFixed(2)}</td></tr>)}</tbody></Table></Tab><Tab eventKey="reportes" title="Reportes"><Alert variant="info">Reportes de ventas, compras, inventario y citas con filtros disponibles en la API.</Alert><Form.Select value={tipoReporte} onChange={e=>setTipoReporte(e.target.value)}><option value="ventas">Ventas</option><option value="compras">Compras</option><option value="inventario">Inventario</option><option value="citas">Citas</option></Form.Select><Button className="mt-3" onClick={cargarReporte}>Generar reporte</Button>{reporte !== null && <pre className="mt-3 bg-light p-3" style={{maxHeight:400,overflow:"auto"}}>{JSON.stringify(reporte,null,2)}</pre>}</Tab></Tabs></div>;
}
