/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ojofinal.glb -t -o src/components/examenes/OjoFinalModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere032: THREE.Mesh
    Sphere032_1: THREE.Mesh
    Sphere032_2: THREE.Mesh
    Sphere038: THREE.Mesh
    Sphere038_1: THREE.Mesh
    Sphere038_2: THREE.Mesh
    Sphere033: THREE.Mesh
    Sphere033_1: THREE.Mesh
    Lens001: THREE.Mesh
    Lens002: THREE.Mesh
    Sphere039: THREE.Mesh
    Sphere039_1: THREE.Mesh
    Sphere040: THREE.Mesh
    Sphere040_1: THREE.Mesh
    OpticNerve: THREE.Mesh
    Vessel_FarLower: THREE.Mesh
    Vessel_FarUpper: THREE.Mesh
    Vessel_Lower: THREE.Mesh
    Vessel_Lower001: THREE.Mesh
    Vessel_MidLower: THREE.Mesh
    Vessel_MidUpper: THREE.Mesh
    Vessel_Upper: THREE.Mesh
  }
  materials: {
    ['Sclera_Mat.012']: THREE.MeshStandardMaterial
    ['Retina_Mat.012']: THREE.MeshStandardMaterial
    ['Sclera_Mat.013']: THREE.MeshStandardMaterial
    ['Retina_Mat.013']: THREE.MeshStandardMaterial
    ['Lens_Mat.011']: THREE.MeshStandardMaterial
    ['Lens_Mat.013']: THREE.MeshStandardMaterial
    ['Lens_Mat.014']: THREE.MeshStandardMaterial
    ['Lens_Mat.016']: THREE.MeshStandardMaterial
    ['Lens_Mat.017']: THREE.MeshStandardMaterial
    ['Lens_Mat.018']: THREE.MeshStandardMaterial
    ['Lens_Mat.019']: THREE.MeshStandardMaterial
    ['Nerve_Mat.011']: THREE.MeshStandardMaterial
    ['Vessels_Mat.011']: THREE.MeshStandardMaterial
    ['Vessels_Mat.012']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ojofinal.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.92, 0.93]}>
        <mesh geometry={nodes.Sphere038.geometry} material={nodes.Sphere038.material} />
        <mesh geometry={nodes.Sphere038_1.geometry} material={materials['Sclera_Mat.013']} />
        <mesh geometry={nodes.Sphere038_2.geometry} material={materials['Retina_Mat.013']} />
      </group>
      <group position={[0, 0, -0.926]} rotation={[Math.PI / 2, 0, 0]} scale={[1.89, 1.73, 1.94]}>
        <mesh geometry={nodes.Sphere033.geometry} material={materials['Lens_Mat.011']} />
        <mesh geometry={nodes.Sphere033_1.geometry} material={materials['Lens_Mat.013']} />
      </group>
      <mesh geometry={nodes.Lens001.geometry} material={materials['Lens_Mat.014']} position={[0, 0, -0.412]} rotation={[Math.PI / 2, 0, 0]} scale={[0.7, 0.7, 0.77]} />
      <mesh geometry={nodes.Lens002.geometry} material={materials['Lens_Mat.013']} position={[0, 0, -1.038]} rotation={[Math.PI / 2, 0, 0]} scale={[1.73, 1.73, 1.66]} />
      <group position={[0, 0, -1.442]} rotation={[Math.PI / 2, 0, 0]} scale={[0.9, 0.82, 0.93]}>
        <mesh geometry={nodes.Sphere039.geometry} material={materials['Lens_Mat.016']} />
        <mesh geometry={nodes.Sphere039_1.geometry} material={materials['Lens_Mat.017']} />
      </group>
      <group position={[-0.005, 0, -1.545]} rotation={[Math.PI / 2, 0, 0]} scale={[1.12, 0.56, 1.12]}>
        <mesh geometry={nodes.Sphere040.geometry} material={materials['Lens_Mat.018']} />
        <mesh geometry={nodes.Sphere040_1.geometry} material={materials['Lens_Mat.019']} />
      </group>
      <mesh geometry={nodes.OpticNerve.geometry} material={materials['Nerve_Mat.011']} position={[0, 0, 0.257]} />
      <mesh geometry={nodes.Vessel_FarLower.geometry} material={materials['Vessels_Mat.011']} position={[-0.23, 0, 0]} rotation={[-0.096, 0, 0]} />
      <mesh geometry={nodes.Vessel_FarUpper.geometry} material={materials['Vessels_Mat.011']} position={[-0.23, 0, -0.06]} />
      <mesh geometry={nodes.Vessel_Lower.geometry} material={materials['Vessels_Mat.011']} position={[-0.23, 0, 0]} rotation={[0.141, 0, 0.583]} />
      <mesh geometry={nodes.Vessel_Lower001.geometry} material={materials['Vessels_Mat.012']} position={[-0.1, 0.374, -0.021]} rotation={[0.229, -0.103, 0.604]} />
      <mesh geometry={nodes.Vessel_MidLower.geometry} material={materials['Vessels_Mat.011']} />
      <mesh geometry={nodes.Vessel_MidUpper.geometry} material={materials['Vessels_Mat.011']} />
      <mesh geometry={nodes.Vessel_Upper.geometry} material={materials['Vessels_Mat.011']} />
      <mesh geometry={nodes.Sphere032.geometry} material={nodes.Sphere032.material} />
      <mesh geometry={nodes.Sphere032_1.geometry} material={materials['Sclera_Mat.012']} />
      <mesh geometry={nodes.Sphere032_2.geometry} material={materials['Retina_Mat.012']} />
    </group>
  )
}

useGLTF.preload('/ojofinal.glb')
