/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ojo_humano.glb -t -o src/components/examenes/OjoImportadoModel.tsx 
Author: SAV. Universidad de Sevilla (https://sketchfab.com/realidadaumentadasav)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ojo-humano-ii-estructuras-externas-asociadas-81e54aa6d8924fb39d7f1a935c438613
Title: Ojo humano II: Estructuras externas asociadas
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_43: THREE.Mesh
    Object_45: THREE.Mesh
    Object_47: THREE.Mesh
    Object_49: THREE.Mesh
    Object_51: THREE.Mesh
    Object_53: THREE.Mesh
    Object_55: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_31: THREE.Mesh
    Object_40: THREE.Mesh
    Object_41: THREE.Mesh
  }
  materials: {
    ESCLEROTICA: THREE.MeshStandardMaterial
    CORNEA: THREE.MeshStandardMaterial
    CRISTALINO: THREE.MeshStandardMaterial
    CARA_BACK: THREE.MeshStandardMaterial
    CARA_FRONT: THREE.MeshStandardMaterial
    CARA_BORDE: THREE.MeshStandardMaterial
    Iris_superior_izquierda: THREE.MeshStandardMaterial
    Coroide__interior_alto: THREE.MeshStandardMaterial
    Iris_superior_derecha: THREE.MeshStandardMaterial
    BORDE_MACULA_COROIDE_ALTA: THREE.MeshStandardMaterial
    coroide_ext_der: THREE.MeshStandardMaterial
    coroide_ext_izq: THREE.MeshStandardMaterial
    Cookie: THREE.MeshStandardMaterial
    cuerpo_ciliar: THREE.MeshStandardMaterial
    musculo_alto: THREE.MeshStandardMaterial
    musculo_lateral: THREE.MeshStandardMaterial
    cuerpo_vitreo: THREE.MeshPhysicalMaterial
    ['ESCLEROTICA.001']: THREE.MeshStandardMaterial
    IRIS: THREE.MeshStandardMaterial
    globo_ocular_parte_interior_baja: THREE.MeshStandardMaterial
    BORDE_GLOBO_OCULAR_BAJA: THREE.MeshStandardMaterial
    ARTERIA: THREE.MeshStandardMaterial
    vena: THREE.MeshStandardMaterial
    Nervio_optico: THREE.MeshStandardMaterial
    base_craneo: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/ojo_humano.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -3.098]} scale={0.016}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="5_ESCLEROTICA_SUPERIOR_1" position={[0, -1.237, 9.038]} rotation={[0, 0, Math.PI]} scale={9.042}>
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.ESCLEROTICA} />
              </group>
              <group name="7_CORNEA_2" position={[0, -1.254, -9.513]} rotation={[Math.PI / 2, 0, 0]} scale={1.177}>
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.CORNEA} />
              </group>
              <group name="8_CRISTALINO_3" position={[0.008, -1.234, -1.071]} rotation={[Math.PI / 2, 0, 0]} scale={0.816}>
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.CRISTALINO} />
              </group>
              <group name="11_CARA_4" position={[0.466, -0.775, 1.445]} rotation={[1.538, 0.002, -0.06]}>
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.CARA_BACK} />
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.CARA_FRONT} />
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.CARA_BORDE} />
              </group>
              <group name="4_MACULA_RETINA_COROIDE_9" position={[0, -1.237, 9.038]} rotation={[0, 0, Math.PI]} scale={9.042}>
                <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Iris_superior_izquierda} />
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Coroide__interior_alto} />
                <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Iris_superior_derecha} />
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.BORDE_MACULA_COROIDE_ALTA} />
                <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.coroide_ext_der} />
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.coroide_ext_izq} />
              </group>
              <group name="9_GLANDULA_13" position={[9.319, 8.394, -3.098]} rotation={[0, 0, -0.234]} scale={[0.741, 0.682, 0.939]}>
                <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Cookie} />
              </group>
              <group name="14_CUERPO_CILIAR_14" position={[0, -1.27, -5.303]} rotation={[Math.PI / 2, 0, 0]} scale={[0.922, 0.925, 0.922]}>
                <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.cuerpo_ciliar} />
              </group>
              <group name="15_MUSCULO_ALTO_15" position={[-6.915, 1.803, 35.532]} rotation={[-0.059, -0.063, -0.003]} scale={[8.578, 10.385, 10.475]}>
                <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.musculo_alto} />
              </group>
              <group name="16_MUSCULO_LATERAL_16" position={[11.708, -2.227, 0.724]}>
                <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.musculo_lateral} />
              </group>
              <group name="9_GLANDULA001_17" position={[8.333, 7.273, -2.571]} rotation={[0.017, 0.004, -0.201]} scale={[0.436, 0.401, 0.553]}>
                <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.Cookie} />
              </group>
              <group name="15_MUSCULO_ALTO001_18" position={[-6.915, 1.803, 35.532]} rotation={[-0.085, -0.124, -0.017]} scale={[5.844, 9.237, 9.306]}>
                <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.musculo_alto} />
              </group>
              <group name="17_CUERPO_VITREO_19" position={[-0.035, -1.303, 0.746]} rotation={[Math.PI / 2, 0, 0]} scale={[1.169, 1.081, 1.169]}>
                <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.cuerpo_vitreo} />
              </group>
              <group name="18_LIGAMENTOS_CRISTALINO_20" position={[3.88, -1.546, -6.068]} rotation={[Math.PI / 2, 0, 0]} scale={0.816} />
              <group name="3_GLOBO_OCULAR_PARTE_BAJA_0" position={[0, -1.237, 9.038]} rotation={[0, 0, Math.PI]} scale={9.042}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['ESCLEROTICA.001']} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.IRIS} />
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.globo_ocular_parte_interior_baja} />
                <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.BORDE_GLOBO_OCULAR_BAJA} />
              </group>
              <group name="1_ARTERIA_interior_5" position={[-3.748, -1.237, 8.543]}>
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.ARTERIA} />
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.ARTERIA} />
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.ARTERIA} />
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.ARTERIA} />
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.ARTERIA} />
              </group>
              <group name="2_VENA_interior_6" position={[-3.631, -1.203, 8.519]} rotation={[0, 0, Math.PI]}>
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.vena} />
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.vena} />
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.vena} />
              </group>
              <group name="12_NERVIO_OPTICO_7" position={[-13.61, -1.169, 49.391]} rotation={[1.567, 0, 0]}>
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Nervio_optico} />
              </group>
              <group name="13_NERVIO_OPTICO_ESCLE_8" position={[-13.61, -1.169, 49.391]} rotation={[1.567, 0, 0]}>
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.ESCLEROTICA} />
              </group>
              <group name="6_BASE_CRANEO_12" rotation={[Math.PI / 2, 0, 0]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.base_craneo} />
                <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.base_craneo} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ojo_humano.glb')
